apiVersion: v1
kind: ConfigMap
metadata:
  name: machine-controller-manager-monitoring-config
  namespace: {{ .Release.Namespace }}
  labels:
    extensions.gardener.cloud/configuration: monitoring
data:
  alerting_rules: |
    machine-controller-manager.rules.yaml: |
      groups:
      - name: machine-controller-manager.rules
        rules:
        - alert: MachineControllerManagerDown
          expr: absent(up{job="machine-controller-manager"} == 1)
          for: 15m
          labels:
            service: machine-controller-manager
            severity: critical
            type: seed
            visibility: operator
          annotations:
            description: There are no running machine controller manager instances. No shoot nodes can be created/maintained.
            summary: Machine controller manager is down.

  dashboard_operators: |
    machine-controller-manager-dashboard.json: |-
{{ .Files.Get "mcm-monitoring-dashboard.json" | indent 6 }}
