{
 "title": "Machine Controller Manager",
 "description": "Information about the operations of the Machine Controller Manager",
 "tags": [
  "controlplane",
  "seed"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "controlloop",
    "label": "Control Loop",
    "query": "machine, machineset, machinedeployment, node, secret, machinesafetyapiserver, machinesafetyorphanvms, machinesafetyovershooting"
   }
  ]
 },
 "panels": [
  {
   "title": "Managed Machines States",
   "type": "graph",
   "description": "State of the managed machines.\n\n| Code | Machine State |\n|---|---|\n| 0 | Running |\n| 1 | Terminating |\n| 2 | Unknown |\n| 3 | Failed |\n| -1 | Available |\n| -2 | Pending |",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mcm_machine_current_status_phase",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "MCM CPU usage",
   "type": "graph",
   "description": "Shows the CPU usage of the Machine Controller Manager and shows the requests and limits.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"machine-controller-manager-(.+)\"}[5m])) by (pod)",
     "legendFormat": "Current ({{pod}})"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", pod=~\"machine-controller-manager-(.+)\"}) by (pod)",
     "legendFormat": "Limits ({{pod}})"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", pod=~\"machine-controller-manager-(.+)\"}) by (pod)",
     "legendFormat": "Requests ({{pod}})"
    }
   ]
  },
  {
   "title": "MCM Memory Usage",
   "type": "graph",
   "description": "Shows the memory usage of the Machine Controller Manager.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"machine-controller-manager-(.+)\"}) by (pod)",
     "legendFormat": "Current ({{pod}})"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", pod=~\"machine-controller-manager-(.+)\"}) by (pod)",
     "legendFormat": "Limits ({{pod}})"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", pod=~\"machine-controller-manager-(.+)\"}) by (pod)",
     "legendFormat": "Requests ({{pod}})"
    }
   ]
  },
  {
   "title": "MCM Frozen Status (API Server reachable)",
   "type": "graph",
   "description": "Indicates if the Machine Controller Manager is frozen due to unreachable API server.\n\n0 = ok; 1= frozen",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mcm_machine_controller_frozen", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "IaaS API Calls",
   "type": "graph",
   "description": "Average per Second rate over 1m of IaaS provider api calls split by services. \n\nShows also the rate of failed iaas calls if at least one failed.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mcm_cloud_api_requests_total[1m])",
     "legendFormat": "{{provider}} / {{service}} ({{pod}})"
    },
    {
     "expr": "rate(mcm_cloud_api_requests_failed_total[1m])",
     "legendFormat": "Error: {{provider}} / {{service}} ({{pod}})"
    }
   ]
  },
  {
   "title": "Count of Managed Resources",
   "type": "graph",
   "description": "The count of kubernetes resources managed by the Machine Controller Manager.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mcm_machine_items_total", "legendFormat": "machine(s)" },
    { "expr": "mcm_machine_set_items_total", "legendFormat": "machine set(s)" },
    {
     "expr": "mcm_machine_deployment_items_total",
     "legendFormat": "machine deployment(s)"
    }
   ]
  },
  { "title": "Control Loops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Workqueue item processing time: ${controlloop}",
   "type": "graph",
   "description": "Average processing time of items in the workqueue.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "${controlloop}_work_duration{quantile=\"0.5\"}",
     "legendFormat": "p50 ({{pod}})"
    },
    {
     "expr": "${controlloop}_work_duration{quantile=\"0.9\"}",
     "legendFormat": "p90 ({{pod}})"
    },
    {
     "expr": "${controlloop}_work_duration{quantile=\"0.99\"}",
     "legendFormat": "p99 ({{pod}})"
    }
   ]
  },
  {
   "title": "Workqueue item latency: ${controlloop}",
   "type": "graph",
   "description": "How long items stay in the workqueue before they get processed.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "${controlloop}_queue_latency{quantile=\"0.5\"}",
     "legendFormat": "p50 ({{pod}})"
    },
    {
     "expr": "${controlloop}_queue_latency{quantile=\"0.9\"}",
     "legendFormat": "p90 ({{pod}})"
    },
    {
     "expr": "${controlloop}_queue_latency{quantile=\"0.99\"}",
     "legendFormat": "p99 ({{pod}})"
    }
   ]
  },
  {
   "title": "Items in Workqueue: ${controlloop}",
   "type": "graph",
   "description": "Current amount of items in the workqueue.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "${controlloop}_depth", "legendFormat": "${controlloop} ({{pod}})" }
   ]
  },
  {
   "title": "Adds to Workqueue: ${controlloop}",
   "type": "graph",
   "description": "Average per second rate over 5m of workqueue item adds.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(${controlloop}_adds[5m])", "legendFormat": "${controlloop} ({{pod}})" }
   ]
  },
  {
   "title": "Workqueue item retries: ${controlloop}",
   "type": "graph",
   "description": "Average per second rate over 5m of workqueue item retries.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(${controlloop}_retries[5m])",
     "legendFormat": "${controlloop} ({{pod}})"
    }
   ]
  }
 ]
}