images:
  machine-controller-manager: image-repository:image-tag
  machine-controller-manager-provider-metal: image-repository:image-tag

replicas: 1

podAnnotations: {}

podLabels: {}

providerName: provider-foo

# injected by generic worker actuator
genericTokenKubeconfigSecretName: generic-token-kubeconfig

namespace:
  uid: uuid-of-namespace

metricsPort: 10258
metricsPort2: 10259

vpa:
  enabled: true
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    mcm:
      maxAllowed:
        cpu: 2
        memory: 5G
    mcmProviderMetal:
      maxAllowed:
        cpu: 2
        memory: 5G

resources:
  mcm:
    requests:
      cpu: 31m
      memory: 70Mi
  mcmProviderMetal:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: "2"
      memory: 5G
