{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: to-metal-api
spec:
  egress:
    - ports:
        - port: 8080
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicies.toMetalApi.namespace }}
        - podSelector:
            matchLabels: {{ .Values.networkPolicies.toMetalApi.ingressController.podSelector | nindent 12 }}
    - ports:
        - port: 80
          protocol: TCP
        - port: 443
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicies.toMetalApi.ingressController.namespace }}
        - podSelector: {}
  podSelector:
    matchLabels:
      networking.resources.gardener.cloud/to-metal-api: allowed
  policyTypes:
    - Egress
{{- end }}
