---
apiVersion: v1
kind: Namespace
metadata:
  name: firewall
---
apiVersion: metal-stack.io/v1
kind: Firewall
metadata:
  namespace: firewall
  name: firewall
spec:
{{ toYaml .Values.firewallSpec | indent 2 }}
status:
  stats: {}
