apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  revisionHistoryLimit: 5
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "labels" . | indent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.kubeconfig }}
        checksum/gardener-extension-admission-metal-kubeconfig: {{ include (print $.Template.BasePath "/secret-kubeconfig.yaml") . | sha256sum }}
        {{- end }}
      labels:
        networking.gardener.cloud/to-dns: allowed
        networking.resources.gardener.cloud/to-virtual-garden-kube-apiserver-tcp-443: allowed
        networking.gardener.cloud/to-runtime-apiserver: allowed
{{ include "labels" . | indent 8 }}
    spec:
      {{- if .Values.gardener.runtimeCluster.priorityClassName }}
      priorityClassName: {{ .Values.gardener.runtimeCluster.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ include "name" . }}
      {{- if .Values.kubeconfig }}
      automountServiceAccountToken: false
      {{- end }}
      containers:
      - name: {{ include "name" . }}
        image: {{ include "image" .Values.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-metal-hyper
        - admission-metal
        - --webhook-config-server-port={{ .Values.webhookConfig.serverPort }}
        {{- if .Values.gardener.virtualCluster.enabled }}
        - --webhook-config-mode=url
        - --webhook-config-url={{ printf "%s.%s" (include "name" .) (.Release.Namespace) }}
        {{- else }}
        - --webhook-config-mode=service
        {{- end }}
        - --webhook-config-namespace={{ .Release.Namespace }}
        {{- if .Values.kubeconfig }}
        - --kubeconfig=/etc/gardener-extension-admission-metal/kubeconfig/kubeconfig
        {{- end }}
        {{- if .Values.projectedKubeconfig }}
        - --kubeconfig={{ required ".Values.projectedKubeconfig.baseMountPath is required" .Values.projectedKubeconfig.baseMountPath }}/kubeconfig
        {{- end }}
        {{- if .Values.metricsPort }}
        - --metrics-bind-address=:{{ .Values.metricsPort }}
        {{- end }}
        - --health-bind-address=:{{ .Values.healthPort }}
        - --leader-election-id={{ include "leaderelectionid" . }}
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.healthPort }}
            scheme: HTTP
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.healthPort }}
            scheme: HTTP
          initialDelaySeconds: 5
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.gardener.virtualCluster.enabled }}
        - name: SOURCE_CLUSTER
          value: enabled
        {{- end }}
{{- range $key, $value := .Values.defaulter }}
{{- if ne nil $value }}
        - name: DEFAULTER_{{ upper $key }}
          value: {{ $value | quote }}
{{- end }}
{{- end }}
        ports:
        - name: webhook-server
          containerPort: {{ .Values.webhookConfig.serverPort }}
          protocol: TCP
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | nindent 10 }}
{{- end }}
        volumeMounts:
        {{- if .Values.kubeconfig }}
        - name: gardener-extension-admission-metal-kubeconfig
          mountPath: /etc/gardener-extension-admission-metal/kubeconfig
          readOnly: true
        {{- end }}
      volumes:
      {{- if .Values.kubeconfig }}
      - name: gardener-extension-admission-metal-kubeconfig
        secret:
          secretName: gardener-extension-admission-metal-kubeconfig
          defaultMode: 420
      {{- end }}
