---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-vpn
  namespace: firewall
spec:
  egress:
  - ports:
    - port: 4314
      protocol: UDP
    - port: 4314
      protocol: TCP
    to:
    - cidr: 0.0.0.0/0
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-dns
  namespace: firewall
spec:
  egress:
  - to:
    - cidr: 0.0.0.0/0
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
{{- if .Values.cwnps.allowHttps }}
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-https
  namespace: firewall
spec:
  egress:
  - to:
    - cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
{{- end }}
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-http
  namespace: firewall
spec:
  egress:
  - to:
    - cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 80
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-ntp
  namespace: firewall
spec:
  egress:
  - to:
    - cidr: 0.0.0.0/0
    ports:
    - protocol: UDP
      port: 123
{{- if .Values.duros.enabled }}
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-storage
  namespace: firewall
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 4420
      protocol: TCP
    - port: 8009
      protocol: TCP
    to:
{{ range $i, $endpoint := .Values.duros.endpoints }}
    - cidr: {{ (split ":" $endpoint)._0 }}/32
{{- end }}
{{- end }}
{{- if gt (len .Values.apiserverIPs) 0 }}
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-apiserver
  namespace: firewall
spec:
  egress:
  - to:
{{- range $i, $ip := .Values.apiserverIPs }}
    - cidr: {{ $ip }}/32
{{- end }}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 8443
    - protocol: TCP
      port: 8132
{{- end }}
