---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-dns
  namespace: firewall
spec:
  egress:
  - to:
    {{- range $dest := .Values.networkAccess.dnsCidrs }}
    - cidr: {{ $dest }}
    {{- end }}
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-ntp
  namespace: firewall
spec:
  egress:
  - to:
    {{- range $dest := .Values.networkAccess.ntpCidrs }}
    - cidr: {{ $dest }}
    {{- end }}
    ports:
    - protocol: UDP
      port: 123
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-vpn
  namespace: firewall
spec:
  egress:
  - ports:
    - port: 4314
      protocol: UDP
    - port: 4314
      protocol: TCP
    to:
  {{- range $i, $ip := .Values.apiserverIPs }}
      - cidr: {{ $ip }}/32
  {{- end }}
{{- if .Values.networkAccess.restrictedOrForbidden }}
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-registry
  namespace: firewall
spec:
  egress:
  {{- range $i, $reg := .Values.networkAccess.registryMirrors }}
  - to:
    - cidr: {{ quote $reg.cidr }}
    ports:
    - protocol: TCP
      port: {{ $reg.port }}
  {{- end }}
{{- end }}
# FIXME remove and replace with appropriate cwnp based on networkAccessType
{{- if .Values.restrictEgress.enabled }}
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-apiserver
  namespace: firewall
spec:
  egress:
  - toFQDNs:
    - matchName: {{ quote .Values.restrictEgress.apiServerIngressDomain }}
    ports:
    - protocol: TCP
      port: 443
    - protocol: UDP
      port: 4314
    - protocol: TCP
      port: 4314
    - protocol: TCP
      port: 8443
    - protocol: TCP
      port: 8132
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-external-dependencies
  namespace: firewall
spec:
  egress:
{{- range $i, $dest := .Values.restrictEgress.destinations }}
  - toFQDNs:
{{- if $dest.matchPattern }}
    - matchPattern: {{ quote $dest.matchPattern }}
{{- else }}
    - matchName: {{ quote $dest.matchName }}
{{- end }}
    ports:
    - protocol: {{ $dest.protocol }}
      port: {{ $dest.port }}
{{- end }}

{{- else }}
{{- if not .Values.networkAccess.restrictedOrForbidden }}
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-https
  namespace: firewall
spec:
  egress:
  - to:
    - cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-http
  namespace: firewall
spec:
  egress:
  - to:
    - cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 80
{{- end }}
{{- if gt (len .Values.apiserverIPs) 0 }}
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-apiserver
  namespace: firewall
spec:
  egress:
  - to:
{{- range $i, $ip := .Values.apiserverIPs }}
    - cidr: {{ $ip }}/32
{{- end }}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 8443
    - protocol: TCP
      port: 8132
{{- end }}
{{- end }}

{{- if .Values.duros.enabled }}
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-storage
  namespace: firewall
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 4420
      protocol: TCP
    - port: 8009
      protocol: TCP
    to:
{{ range $i, $endpoint := .Values.duros.endpoints }}
    - cidr: {{ (split ":" $endpoint)._0 }}/32
{{- end }}
{{- end }}
