---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:controller:cloud-node-controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - delete
  - get
  - patch
  - update
  - list
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:controller:cloud-node-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:cloud-node-controller
subjects:
- kind: ServiceAccount
  name: cloud-node-controller
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-controller-manager
rules:
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
    - update
- apiGroups:
    - ""
  resources:
    - nodes
  verbs:
    - "*"
- apiGroups:
    - ""
  resources:
    - nodes/status
  verbs:
    - patch
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - services/status
  verbs:
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - serviceaccounts
    - serviceaccounts/token
  verbs:
    - create
    - get
    - list
    - watch
    - update
- apiGroups:
    - ""
  resources:
    - persistentvolumes
  verbs:
    - get
    - list
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - endpoints
  verbs:
    - create
    - get
    - list
    - watch
    - update
- apiGroups:
    - ""
  resources:
    - secrets
    - configmaps
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - get
    - create
    - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-controller-manager
subjects:
- kind: ServiceAccount
  name: cloud-controller-manager
  namespace: kube-system
